### ISSUE TITLE
为什么在pdm install时发生错误

### ISSUE THREAD

**Issue by weyctor** [yaowan233/miyuki#1]
x Install graiax-silkcoder 0.3.6 failed
  x Install asyncmy 0.2.9 failed

**Comment by yaowan233** [comment]
> x Install graiax-silkcoder 0.3.6 failed
>   x Install asyncmy 0.2.9 failed

请提供python版本还有系统环境

**Comment by weyctor** [comment]
Python 3.13.0 win10专业版21H2

**Comment by yaowan233** [comment]
> Python 3.13.0 win10专业版21H2

请使用python3.9-3.12版本 3.13还是测试版

**Comment by weyctor** [comment]
我卸载了python3.13 然后下载了python3.12.7并添加到环境，然后重新pdm install，这次是did not find executable at 'C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe': ???????????
看起来它去python313里面找python了？？？

**Comment by weyctor** [comment]
之前进行了一个pdm lock的操作 不知道有没有影响

**Comment by yaowan233** [comment]
> 我卸载了python3.13 然后下载了python3.12.7并添加到环境，然后重新pdm install，这次是did not find executable at 'C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe': ???????????
> 看起来它去python313里面找python了？？？

在系统环境变量的path中将旧的python路径删了

**Comment by weyctor** [comment]
![系统属性 2024_11_1 21_26_32](https://github.com/user-attachments/assets/13f0a453-3f83-46fb-b4e3-c2b7ccffea9d)
我删了，但是pdm install还是一样的效果

**Comment by yaowan233** [comment]
> ![系统属性 2024_11_1 21_26_32](https://private-user-images.githubusercontent.com/119778422/382291592-13f0a453-3f83-46fb-b4e3-c2b7ccffea9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjgwODcsIm5iZiI6MTczMDQ2Nzc4NywicGF0aCI6Ii8xMTk3Nzg0MjIvMzgyMjkxNTkyLTEzZjBhNDUzLTNmODMtNDZmYi1iNGUzLWMyYjdjY2ZmZWE5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMzI5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmUxMzI5NjhkOWIyOTYzYmZkY2M2NDdlMTkyNGE2YjBhOTRhMmY4MWMzNjdhMTRhOWI1ZWFiNmFiNjFjOTJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mZ57Bdi6Y415Oornh5MOhIAntk-BLVtaFozZmJkmuwk) 我删了，但是pdm install还是一样的效果

那就是pdm的问题 重新装pdm 如果还有问题 直接加我qq吧 572473053
